# Common properties

defaultpage: /pages/ldserver.html
SPARQLRetrieveResourceQuery: DESCRIBE <{0}>
SPARQLASKResourceQuery: ASK '{' '{' <{0}> ?p ?o '}' UNION  '{' ?s ?p <{0}> '}' '}'
xslt: replicate.xsl
SPARQLendpoint: sparql

#Global properties
triplestore: http://localhost:9999/blazegraph/namespace/guerracivileuskadi/sparql
host: http://localhost:8080/ROOT/

#Datasets resources properties

base: http://guerracivileuskadi.eurohelp.es




#Predicates properties

# Replicate properties

#triplestore: http://haproxy/blazegraph/sparql
#base: http://donostia.eus/data
#host: http://localhost:8080/data/

