# Common properties

defaultpage: /pages/ldserver.html
SPARQLRetrieveResourceQuery: DESCRIBE <{0}>
SPARQLASKResourceQuery: ASK '{' '{' <{0}> ?p ?o '}' UNION  '{' ?s ?p <{0}> '}' '}'
xslt: replicate.xsl
SPARQLendpoint: sparql

#Global properties
triplestore: http://localhost:8080/blazegraph/namespace/kb/sparql
host: http://guerracivileuskadi.eurohelp.es/linkeddata
base: http://guerracivileuskadi.eurohelp.es/linkeddata

#triplestore: http://haproxy/blazegraph/sparql
#base: http://donostia.eus/data
#host: http://localhost:8080/data/
